- alias: Motion Sensor Lights On Entrance
  trigger:
    platform: time_pattern
    minutes: "/1"
  condition: 
    condition: numeric_state
    below: 80
    "entity_id": "sensor.lightlevel_24"
  action:
    - service: light.turn_on
      data:
        brightness: >
          {%- set lux = states.sensor.room1_lux.state | int -%}
          {%- set perc = (1000 - lux) / (1000 / 100) | int -%}
          {{ ((76.5 * perc) / 100) | int }}
        "entity_id": "light.philips_hue_white_amb_entrance"
        
- alias: Motion Sensor Lights Off Entrance
  trigger:
    platform: time_pattern
    minutes: "/1"
  condition: 
    condition: numeric_state
    above: 80
    "entity_id": "sensor.lightlevel_24"
  action:
    - service: light.turn_off
      data:
        "entity_id": "light.philips_hue_white_amb_entrance"
