- alias: 'Turn lights on when the sun gets dim'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition: []
  action:
    service: light.turn_on
    data_template:
      entity_id: light.garage
      brightness: 50
      transition: 30