- alias: Control permanent light phase
  trigger:
  - platform: sun
    event: sunset
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - data:
      entity_id: input_boolean.permanent_light_phase
    service_template: >
      input_boolean.turn_{% if trigger.platform == 'time' %}off{% else %}on{% endif %}
          
- alias: Turn on kitchen window lights when movement
  trigger:
    platform: state
    entity_id: binary_sensor.presence_26
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.permanent_light_phase
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - data:
      entity_id: light.aqara_white_kitchen_window
    service_template: homeassistant.turn_{{ trigger.to_state.state | lower }}