- alias: 'Turn lights on when the sun gets dim'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition: []
  action:
    service: light.turn_on
    data_template:
      entity_id: light.living_room
      brightness_pct: '{% if states.sun.sun.attributes.elevation <= -35 %}10{% elif states.sun.sun.attributes.elevation <= -22 %}25{% elif states.sun.sun.attributes.elevation > -15 %}50{% elif states.sun.sun.attributes.elevation > -6 %}75{% elif states.sun.sun.attributes.elevation > -6 %}100{% else %}0{% endif %}'
      transition: 30